{% set name = "lixtools" %}
{% set version = "2022.6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c06a1e995f2bfef2c37261e152c223db83a1e5c217082398a996aaf106a91b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - ipython
    - ipywidgets
    - matplotlib-base
    - numpy
    # - opencv
    - openpyxl >=3
    # - opentrons  # per Lin Yang, that dependendency is not needed for the main code base, as it's used separately.
    - pandas
    - pillow
    - py4xs
    - python-barcode
    # - pyzbar
    - qrcode
    - scipy

test:
  imports:
    - lixtools
    - lixtools.atsas
    - lixtools.hdf
    - lixtools.mailin
    - lixtools.modeling
    - lixtools.notebooks
    # - lixtools.ot2  # per Lin Yang, that dependendency is not needed for the main code base, as it's used separately.
    # - lixtools.webcam  # see the comment above.

  commands:
    - python -c "import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename('lixtools', 'plate_label_template.html'))"
    - python -c "import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename('lixtools', 'template_report.ipynb'))"

about:
  home: https://github.com/NSLS-II-LIX/lixtools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Software tools for data collection/processing at NSLS-II LiX

extra:
  recipe-maintainers:
    - lyang11973
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
